### ISSUE TITLE
digBlock doesn't break blocks with break time.

### ISSUE THREAD

**Issue by nuvasuper** [woder/TorchBot#13]
In the cases I've tested, (breaking sand, cobble, sapling, torch, and tripwire with hand, breaking cobble with stone pick) 
The break animation seems to play though, but the block isn't broken unless the block has no time required to break (sapling, torch, tripwire, etc)
I don't have a full understanding of the Minecraft protocol, so I can't figure out where exactly the problem is.  I would guess somewhere in the World code?

**Comment by nuvasuper** [comment]
Fixed my personal IDE issues, now we need to have World implement the relevant methods of BlockInfoManager and BlockInfo.  It might be worthwhile to combine Block and BlockInfo into one object, since they both store information about a block, the only difference being that BlockInfo is about all blocks of a certain id and metadata, while Block is about a specific block in the world.

**Comment by woder** [comment]
That sounds like a pretty good idea but I would suggest that you should combine BlockInfo into Block because Block is used in a lot of places. (And the name fits better)

**Comment by Alderin1974** [comment]
I might be way off, so ignore me as appropriate: Perhaps simply move
BlockInfo to a subclass of Block, and future access is Block.Info (or
Block->Info).

If I had time, I'd look up all the code and make actually helpful comments.
:-)

**Comment by nuvasuper** [comment]
I moved the variables that BlockInfo held and the relevant methods and put them in Block.  World should also be giving any Blocks returned by the getBlock methods their proper hardness, name, and tool.  I think the next step is to change any digBlock methods to use the getBreakTime method that Block now provides.
