### ISSUE TITLE
build.torchbot.net link is broken or down

### ISSUE THREAD

**Issue by pokeball99** [woder/TorchBot#14]

**Comment by woder** [comment]
Working on this currently, had a server change it should be up by tomorrow.

**Comment by pokeball99** [comment]
thank's for responding

**Comment by pokeball99** [comment]
and it seams to be up as well right now

**Comment by woder** [comment]
yes, its not working properly though, the jdk doesn't seem to be installed, wont take long.

**Comment by woder** [comment]
And it is now functional.
