### ISSUE TITLE
A suggestion that would make this client used ALOT more

### ISSUE THREAD

**Issue by Tezma** [woder/TorchBot#16]
I am in need of a add on that notifies my when a player enters my radar, so for instance I want to place 10+ alts all around my factions base then whenever a player enters the radar of the bot it will automatically /msg the selected player that you want to notify with the players name, for example. <BotName> would /msg <PlayerSelectedToNotify> <PlayerDetectedsName> is withing your base's radius. would be very appreciated if you could add this, thanks.

**Comment by nuvasuper** [comment]
That doesn't sound difficult to code at all, just make a list that keeps
track of already known players, and a loop that handles all new players in
the list of entities by sending your message.

**Comment by Tezma** [comment]
Also if you could make make it so each bot has a seperate txt file that it writes the time, date and players name its radar picked up so that if you want to check to see if anyone came by while you were away you can easily see. Honestly if you made all of this working good ALOT and I mean like 200+ factions players would use this. I am planning on doing it if so.

**Comment by nuvasuper** [comment]
You might find yourself running into issues with the server administration
if they consider such behavior hacking.  If they would approve of such
bots, I'd alternatively suggest looking into the SnitchBlock plugin.

**Comment by Tezma** [comment]
Link?

**Comment by nuvasuper** [comment]
I'm sure you can find multiple versions yourself with a simple Google
search.

**Comment by ghost** [comment]
help me how to change the name
